### ISSUE TITLE
Pinger.CHannels.Find isn't a function

### ISSUE THREAD

**Issue by sidph0** [justwolfii/DiscordPinger#2]
(node:4196) UnhandledPromiseRejectionWarning: TypeError: Pinger.channels.find is not a function
    at Timeout._onTimeout (C:\Users\xLunar\Desktop\DiscordPinger\pinger.js:42:51)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)

Any way on how to fix this?

**Comment by IdkWhosThis** [comment]
@xLunar I have just updated DiscordPinger. Delete your current files and download it again. Instead of doing `npm i discord.js`, just run setup.bat (on windows) or setup.sh (on linux) and then start the bot using start.bat/start.sh.
